language: go

sudo: false

go:
    - 1.8.x
    - 1.9.x

before_install:
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls

script:
    - go test -v -parallel=10 -covermode=count -coverprofile=coverage.out
    - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
